import InfoCard from 'components/InfoCard'
import InputField from 'components/InputField'
import Map from 'components/Map'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { GiSittingDog } from 'react-icons/gi'
import { getIpInfo } from 'utils/api'

export default function Home() {
  const [ipAddress, setIpAddress] = useState('')
  const [ipInfo, setIpInfo] = useState({})

  console.log(ipInfo)

  return (
    <>
      <Head>
        <title>IP Watchdog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.nicepng.com/png/full/125-1252485_white-dog-icon-white-dog-icon-transparent-background.png" />
      </Head>
      <main className='w-full h-screen bg-gray-300'>
        <div className='bg-gradient-to-br from-blue-900 to-blue-500 h-[35%] lg:h-[30%] text-center flex flex-col items-center relative'>
          <div className='flex items-center gap-1 pt-6 z-10'>
            <p className='text-white text-3xl'>IP Watchdog </p>
            <img src='https://www.nicepng.com/png/full/125-1252485_white-dog-icon-white-dog-icon-transparent-background.png' className='w-8 text-white' />
          </div>
          <InputField ipAddress={ipAddress} setIpAddress={setIpAddress} setIpInfo={setIpInfo} />
          <InfoCard ipInfo={ipInfo} />
        </div>
        {/* <Map /> */}
      </main>
    </>
  )
}
